# -------------------------------------------------------------------------------------------------
# add node_modules/.bin to PATH + add forge-deploy binary for testing
export PATH := "./node_modules/.bin:" + "../../target/debug:" + env_var('PATH')
# -------------------------------------------------------------------------------------------------

_default:
  @just --choose

# example of how to setup forge-deploy as a local binary
# setup:
#     cargo install --version 0.0.4 --root . forge-deploy

compile:
    forge-deploy gen-deployer && forge build

gen-deployer:
    forge-deploy gen-deployer

export context out:
    forge-deploy export {{context}} {{out}}
sync:
    forge-deploy sync


deploy $MODE="localhost": (compile)
    ldenv just _deploy
_deploy:
    if [ "${MODE}" = "void" ]; then \
        forge script script/DeployGreetingsRegistry.s.sol --private-key $DEPLOYER_PRIVATE_KEY; \
    else \
        forge script script/DeployGreetingsRegistry.s.sol --private-key $DEPLOYER_PRIVATE_KEY -vvvv --rpc-url $RPC_URL --broadcast && forge-deploy sync; \
    fi;

