setup:
    cargo install --locked 0.0.1 --root . forge-deploy

compile:
    forge-deploy gen-deployer && forge build

gen-deployer:
    forge-deploy gen-deployer

sync:
    forge-deploy sync


deploy $MODE="localhost": (compile)
    ldenv just _deploy
_deploy:
    if [ "${MODE}" = "void" ]; then \
        forge script script/DeployGreetingsRegistry.s.sol --private-key $DEPLOYER_PRIVATE_KEY; \
    else \
        forge script script/DeployGreetingsRegistry.s.sol --private-key $DEPLOYER_PRIVATE_KEY -vvvv --rpc-url $RPC_URL --broadcast && forge-deploy sync; \
    fi;


# Testing forge-deploy
export PATH := "./node_modules/.bin:" + "../../target/debug:" + env_var('PATH')

load context:
    ldenv -m {{context}} env

